-- 환자 및 의사의 데이터를 담을 테이블
CREATE TABLE HOSPITAL_MEMBER(
  MEM_NUM INT AUTO_INCREMENT PRIMARY KEY
  , MEM_ID VARCHAR(50) NOT NULL
  , MEM_PW VARCHAR(50) NOT NULL
  , MEM_NAME VARCHAR(30) NOT NULL
  , MEM_TEL VARCHAR(30) UNIQUE
  , MEM_ROLE VARCHAR(30) DEFAULT 'USER'
  , HOSPITAL_CODE VARCHAR(30) DEFAULT 'H4' -- 환자 : h4, 의사 : 진료과에 맞는 코드 선정
  , GENDER VARCHAR(10) NOT NULL
  , BIRTHDAY VARCHAR(40) NOT NULL
  , EMAIL VARCHAR(50) NOT NULL
);

-- 진료예약 및 환자 차트를 조회를 위한 테이블
CREATE TABLE HOSPITAL_RESERVATION (
   RES_NUM INT AUTO_INCREMENT PRIMARY KEY,
   RES_DATE DATE NOT NULL,              -- 예약 날짜
   RES_TIME TIME NOT NULL,              -- 예약 시간
   SERVICE_TYPE VARCHAR(50),            -- 증상
   DISEASE VARCHAR(50), 					 -- 병명	
	SURGERY VARCHAR(30) DEFAULT 'X' ,    -- 수술 여부
	STATUS VARCHAR(20) DEFAULT '예약됨', -- 예약 상태 (예: 예약됨, 완료, 취소됨 등)
   MEM_NUM INT NOT NULL REFERENCES hospital_member(MEM_NUM) ON DELETE CASCADE -- 예약한 회원의 번호
);

-- 고객센터 테이블
CREATE TABLE SERVICE_BOARD(
  BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
  ,BOARD_TITLE VARCHAR(200) NOT NULL
  ,BOARD_CONTENT VARCHAR(500) NOT NULL
  ,BOARD_WRITER VARCHAR(50) NOT NULL
  ,CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP                
);

DROP TABLE hospital_member;
DROP TABLE hospital_reservation;
SELECT * FROM hospital_member;
SELECT * FROM hospital_reservation;
DELETE FROM hospital_member;
DELETE FROM hospital_reservation;
