 -- react 기본 게시판 프로젝트
 CREATE TABLE REACT_BOARD (
 	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	 , BOARD_TITLE VARCHAR(50) NOT NULL
	 , BOARD_CONTENT VARCHAR(100)
	 , BOARD_WRITER VARCHAR(30) NOT NULL
	 , CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
 );
 
 SELECT * FROM REACT_BOARD;
 
 INSERT INTO REACT_BOARD(
 	BOARD_TITLE
 	, BOARD_WRITER
 ) VALUE (
	'세번째 게시글'
	, '김자바'
 );
 
 SELECT BOARD_NUM
 	, BOARD_TITLE
 	, BOARD_WRITER
 	, CREATE_DATE
 FROM REACT_BOARD;
  	
