CREATE TABLE CAR_INFO (
CAR_NUM INT AUTO_INCREMENT PRIMARY KEY -- 모델 번호
, CAR_NAME VARCHAR(50) NOT NULL -- 모델명
, CAR_MONEY INT NOT NULL -- 차량 금액
, CAR_MANUFACTURER VARCHAR(50) NOT NULL -- 차량 제조사
);

SELECT * FROM car_info;

DELETE FROM car_info
WHERE CAR_NUM = 3;

CREATE TABLE SALES_INFO(
SALE_NUM INT AUTO_INCREMENT PRIMARY KEY
, BUYER_NAME VARCHAR(30) NOT NULL
, BUYER_TEL VARCHAR(50)
, COLOR VARCHAR(50) NOT NULL
, SALE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
, CAR_NUM INT NOT NULL REFERENCES CAR_INFO(CAR_NUM));

SELECT * FROM sales_info;
DROP TABLE sales_info;


INSERT INTO CAR_INFO(
            CAR_NAME
            , CAR_MONEY
            , CAR_MANUFACTURER
        ) VALUES(
            'k5'
            , 10000
            , '기아'
        );







DELETE FROM sales_info
WHERE SALE_NUM > 4;