CREATE TABLE REACT_STUDENT(
	STU_NUM INT AUTO_INCREMENT PRIMARY KEY
	, STU_NAME VARCHAR(30) NOT NULL
	, KOR_SCORE INT
	, ENG_SCORE INT
	, MATH_SCORE INT
	, STU_AGE INT
	, STU_TEL VARCHAR(20) UNIQUE -- 010-1111-2222
	, STU_ADDR VARCHAR(50)
);

SELECT * FROM REACT_STUDENT;

DELETE FROM REACT_STUDENT;